### ISSUE TITLE
truffle unbox issue

### ISSUE THREAD

**Issue by adamskrodzki** [DOkwufulueze/eth-vue#14]
Hello,

I've run following commands 
`truffle unbox DOkwufulueze/eth-vue
truffle compile
`

and i get an error

> Error: Cannot find module 'ethereumjs-wallet/hdkey'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/media/adam/Projekty/KATA/truffle.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

my versions are:
Truffle v4.1.12 (core: 4.1.12)
Solidity v0.4.24 (solc-js)

Is this also related to the version of truffle?

ethereumjs-wallet is in node_modules and dist folder contains hdkey.js

**Comment by DOkwufulueze** [comment]
Hi, @adamskrodzki 

I have copied your `unbox` command as typed and pasted same on my terminal, everything worked fine and as expected. I'll share a screenshot of my terminal after executing the command you wrote above.


![screen shot 2018-08-05 at 11 54 37 am](https://user-images.githubusercontent.com/13135088/43685249-742d38d8-98a7-11e8-84dd-91cb5c4c4d9e.png)


So, I guess it's probably the same version issue, not very sure yet as we haven't upgraded. We should be doing that by next 2 weekends.

If there's any other issue you'll like us to know about, please write again, and if you fixed this issue by going down to `Solidity v0.4.18`, also let us know.

Have a blessed day!

**Comment by adamskrodzki** [comment]
Going down to Solidity v0.4.18

fixes the issue. 


Best Regards

Adam

**Comment by DOkwufulueze** [comment]
Thanks a lot for the feedback, @adamskrodzki 

Highly appreciated.

I think it's safe to close this issue now.
